SaApp1/Controllers/InfoController.cs
using SaApp1.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace SaApp1.Controllers
{
    [Authorize]
    public class InfoController : Controller
    {
        private SaApp1DBEntities _db = new SaApp1DBEntities();

        // GET: Info
        public ActionResult Index(LoginUser loginUser)
        {
            return RedirectToAction("Index", "Home");
        }

        // GET: Info/Edit/5
        public ActionResult Edit(int id)
        {
            var realPerson = new RealPerson(id);

            return View(realPerson);
        }

        // POST: Info/Edit/5
        [HttpPost]
        public ActionResult Edit(RealPerson returnedRealPerson)
        {
            try
            {
                var originalPerson = new RealPerson(returnedRealPerson.ID);

                if (!ModelState.IsValid)
                {
                    ViewBag.Message = "Invalid state";
                    return View(returnedRealPerson);
                }

                _db.People.Attach(originalPerson.Person);
                if (originalPerson.PersonInfo != null)
                    _db.PersonInfoes.Attach(originalPerson.PersonInfo);

                var currentPassword = originalPerson.Person.Password;
                _db.Entry(originalPerson.Person).CurrentValues.SetValues(returnedRealPerson.Person);
                if (string.IsNullOrEmpty(originalPerson.Person.Password) || currentPassword != originalPerson.Person.Password.MD5())
                {
                    originalPerson.Person.Password = currentPassword;
                }
                else if (returnedRealPerson.Person.Password.MD5() == currentPassword && returnedRealPerson.NewPassword == returnedRealPerson.ConfirmPassword && !string.IsNullOrEmpty(returnedRealPerson.NewPassword))
                {
                    originalPerson.Person.Password = returnedRealPerson.NewPassword.MD5();
                }

                if (originalPerson.PersonInfo != null)
                {
                    _db.Entry(originalPerson.PersonInfo).CurrentValues.SetValues(returnedRealPerson.PersonInfo);

                }
                else
                {
                    originalPerson.PersonInfo = _db.PersonInfoes.Add(returnedRealPerson.PersonInfo);
                    originalPerson.PersonInfo.PersonId = originalPerson.Person.Id;
                }
                _db.SaveChanges();

                ViewBag.Message = "Information Saved";
                return PartialView(originalPerson);
            }
            // https://stackoverflow.com/questions/7795300/validation-failed-for-one-or-more-entities-see-entityvalidationerrors-propert
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(returnedRealPerson);
            }
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

// https://www.c-sharpcorner.com/UploadFile/0c1bb2/post-data-without-whole-postback/

SaApp1/Views/Info/Edit.cshtml
@model SaApp1.Models.RealPerson

@{
    ViewBag.Title = "Edit your profile:";
}

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

<div id="profile_form">
    <h4>Edit profile</h4>
    @using (Ajax.BeginForm("Edit", "Info", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "profile_form" }))
    {
        @Html.AntiForgeryToken()

        if (User.Identity.IsAuthenticated)
        {

            @Html.HiddenFor(rp => rp.Person.Id)
            @Html.HiddenFor(rp => rp.PersonInfo.Id)
            @Html.HiddenFor(rp => rp.PersonInfo.PersonId)

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(rp => rp.Person.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.Person.Name, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                    </div>
                    @Html.LabelFor(rp => rp.Person.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.Person.Surname, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(rp => rp.PersonInfo.TelNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.PersonInfo.TelNo, htmlAttributes: new { @class = "form-control" })
                    </div>
                    @Html.LabelFor(rp => rp.PersonInfo.CellNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.PersonInfo.CellNo, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(rp => rp.PersonInfo.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.PersonInfo.AddressLine1, htmlAttributes: new { @class = "form-control" })
                    </div>
                    @Html.LabelFor(rp => rp.PersonInfo.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.PersonInfo.AddressLine2, htmlAttributes: new { @class = "form-control" })
                    </div>
                    @Html.LabelFor(rp => rp.PersonInfo.AddressLine3, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.PersonInfo.AddressLine3, htmlAttributes: new { @class = "form-control" })
                    </div>
                    @Html.LabelFor(rp => rp.PersonInfo.AddressCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.PersonInfo.AddressCode, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(rp => rp.PersonInfo.PostalAddress1, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.PersonInfo.PostalAddress1, htmlAttributes: new { @class = "form-control" })
                    </div>
                    @Html.LabelFor(rp => rp.PersonInfo.PostalAddress2, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.PersonInfo.PostalAddress2, htmlAttributes: new { @class = "form-control" })
                    </div>
                    @Html.LabelFor(rp => rp.PersonInfo.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(rp => rp.PersonInfo.PostalCode, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(rp => rp.Person.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.PasswordFor(rp => rp.Person.Password, htmlAttributes: new { @class = "form-control" })
                    </div>
                    @Html.LabelFor(rp => rp.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.PasswordFor(rp => rp.NewPassword, htmlAttributes: new { @class = "form-control" })
                    </div>
                    @Html.LabelFor(rp => rp.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.PasswordFor(rp => rp.ConfirmPassword, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                    <div class="col-md-12 text-success">
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        }
    }
    <div>
        @Html.ActionLink("Sign out", "Logout")
    </div>
</div>